controllers:
    resource: ../../src/Controller/
    type: annotation

api:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api/
    defaults:
        _format: json

kernel:
    resource: ../../src/Kernel.php
    type: annotation
